# Generated by Django 2.2.18 on 2021-08-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
